#START VOXEL STUFF
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 9
mark_threshold: 0
#END VOXEL STUFF
#transform_tolerance: 0.3
#transform_tolerance: 1.0
robot_radius: 0.39
footprint_padding: 0.01
inflation_radius: 0.5
 #0.34, 0.55
cost_scaling_factor: 10.0
observation_sources: scan
scan: {data_type: LaserScan, expected_update_rate: 0.14,
  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 2.4, min_obstacle_height: 0.08}
